Revert "services_autorun: fix for incorrect evaluation"
This reverts commit 452e12ea6a232726af25456e4fce29763a812c9e.
Introduced error messages on clients:

error: Unresolved variable '@(autorun.inputs)' in input list, cannot parse