Guard again enforcing root ownership for CFEngine files on Windows
Trying to enforce user root ownership on $(sys.statedir) and
$(sys.workdir)/modules was causing many errors to be reported:

error: Could not look up name 'root'. (LookupAccountName)

Changelog: title
Ticket: ENT-4628
(cherry picked from commit d6ae4b084610bfd91ac3c20b5fd5b0cf987a0e19)