Fixed error caused by function call in comment attribute
```
$ cf-agent -KI
   error: Comments can only be scalar objects, not 'call' in '$(cfe_internal_hub_vars.docroot)/static/.'
```

Ticket: None
Changelog: None
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>