Fix: suppress error about unknown lvalue
When the variable did not have at least one element cf-hub would emit an
error:

```
   error: Unknown lval exclude_hosts in hub control body
```

Having at lest one list element suppresses this error with no known
side effects.

Changelog: Title
(cherry picked from commit 2cc1555e1537da3a9167e3d730a1da09bacfd3a8)