Fixed bad regex in packages promise method for pip
The packages promise method for pip fails with error:
```
error: Regular expression error: 'invalid range in character class' in expression '^([[:alnum:]-_]+\s\([\d.]+\))' (offset: 13)
```

This is probably a regression after upgrading from PCRE to PCRE2.

The regex engine complains about the hyphen, which has a special meaning
within the square brackets. The bug is easily fixed by escaping the
hyphen.

Ticket: ENT-13667
Changelog: Title
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>
(cherry picked from commit 8871aeffd9dd58b755547aac20b1ce3aa530a8dc)